# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('Contenido', models.TextField(max_length=700)),
                ('url_image', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
