# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ayudantes',
            fields=[
                ('matricula', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ayudantias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=9)),
                ('horaInicio', models.TimeField(verbose_name='Empieza')),
                ('horaFin', models.TimeField(verbose_name='Finaliza')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayudantias.Aulas')),
                ('ayudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayudantias.Ayudantes')),
            ],
        ),
    ]
