# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayudantias', '0002_auto_20170226_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ayudantias',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='ayudantias',
            name='ayudante',
        ),
        migrations.DeleteModel(
            name='Aulas',
        ),
        migrations.DeleteModel(
            name='Ayudantes',
        ),
        migrations.DeleteModel(
            name='Ayudantias',
        ),
    ]
