# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semana', '0002_auto_20170225_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporecurso',
            name='icono',
            field=models.URLField(blank=True),
        ),
    ]
