# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('pre_requisito', models.CharField(max_length=100)),
                ('co_requisito', models.CharField(max_length=10)),
                ('nivel', models.CharField(max_length=10)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
               
            ],
        ),
    ]
