# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='Contenido',
            field=models.TextField(),
        ),
    ]
