# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='file_politicas',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='file_silabus',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='co_requisito',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
