# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20170222_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='co_requisito',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='pre_requisito',
            field=models.TextField(max_length=100),
        ),
    ]
