# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_auto_20170222_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='file_politicas',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='curso',
            name='file_silabus',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
