# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_auto_20170225_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='file_politicas',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='file_silabus',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
